spotipyn:
  debug: ${DEBUG}
  django_secret_key: ${DJANGO_SECRET_KEY}
database:
  name: ${POSTGRESQL_NAME}
  user: ${POSTGRESQL_USER}
  password: ${POSTGRESQL_PASSWORD}
  host: ${POSTGRESQL_HOST}
  port: ${POSTGRESQL_PORT}
